name: Flutter Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test Flutter Package
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Flutter (3.19.6)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🧪 Static Analysis
        run: flutter analyze

      - name: 🧪 Run Unit Tests
        run: flutter test

      - name: ✅ Dry Run Publish
        run: dart pub publish --dry-run
